import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  ArrowRight, 
  ArrowLeft, 
  Plus, 
  Edit, 
  Trash2,
  Hammer,
  Settings,
  PaintBucket,
  Calendar,
  Clock
} from "lucide-react";
import { ProjectWizardData } from "@/lib/types";

interface ActivitiesOverviewProps {
  data: ProjectWizardData;
  onUpdate: (updates: Partial<ProjectWizardData>) => void;
  onNext: () => void;
  onPrevious: () => void;
}

export default function ActivitiesOverview({ data, onUpdate, onNext, onPrevious }: ActivitiesOverviewProps) {
  // Sample activities data based on the design
  const sampleActivities = [
    {
      id: "demolition",
      name: "Demolizioni e Rimozioni",
      icon: Hammer,
      totalArea: "120 m²",
      activities: [
        { id: "1", description: "Rimozione pavimento in legno esistente", location: "Soggiorno", quantity: "27.3", unit: "m²" },
        { id: "2", description: "Demolizione cucina esistente", location: "Cucina", quantity: "14.0", unit: "m²" }
      ]
    },
    {
      id: "electrical",
      name: "Impianti Elettrici",
      icon: Settings,
      totalArea: "15 punti",
      activities: [
        { id: "3", description: "Prese elettriche standard", location: "Soggiorno", quantity: "8", unit: "pz" },
        { id: "4", description: "Punti luce a soffitto", location: "Cucina", quantity: "4", unit: "pz" }
      ]
    },
    {
      id: "finishes",
      name: "Finiture e Rivestimenti",
      icon: PaintBucket,
      totalArea: "85 m²",
      activities: [
        { id: "5", description: "Piastrelle ceramiche per pavimento", location: "Soggiorno", quantity: "27.3", unit: "m²" },
        { id: "6", description: "Tinteggiatura pareti", location: "Soggiorno, Cucina", quantity: "58.0", unit: "m²" }
      ]
    }
  ];

  const handleEditActivity = (activityId: string) => {
    console.log("Edit activity:", activityId);
  };

  const handleDeleteActivity = (activityId: string) => {
    console.log("Delete activity:", activityId);
  };

  const handleAddCategory = () => {
    console.log("Add new category");
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <Card className="shadow-lg animate-fade-in">
        <CardContent className="p-8">
          <div className="mb-8">
            <h2 className="text-3xl font-bold text-text-primary mb-4">Work Activities Overview</h2>
            <p className="text-text-secondary text-lg">
              Review and edit the construction activities generated by AI based on your site visit
            </p>
          </div>

          {/* Activity Categories */}
          <div className="space-y-6">
            {sampleActivities.map((category) => {
              const IconComponent = category.icon;
              return (
                <div key={category.id} className="border border-gray-200 rounded-xl overflow-hidden">
                  <div className="bg-surface-light p-4">
                    <div className="flex items-center justify-between">
                      <h3 className="text-lg font-semibold text-text-primary flex items-center">
                        <IconComponent className="h-5 w-5 text-primary mr-2" />
                        {category.name}
                      </h3>
                      <div className="text-sm text-text-secondary">
                        {category.totalArea}
                      </div>
                    </div>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full">
                      <thead className="bg-gray-50">
                        <tr>
                          <th className="px-4 py-3 text-left text-xs font-medium text-text-secondary uppercase tracking-wider">
                            Description
                          </th>
                          <th className="px-4 py-3 text-left text-xs font-medium text-text-secondary uppercase tracking-wider">
                            Location
                          </th>
                          <th className="px-4 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                            Quantity
                          </th>
                          <th className="px-4 py-3 text-left text-xs font-medium text-text-secondary uppercase tracking-wider">
                            UDM
                          </th>
                          <th className="px-4 py-3 text-center text-xs font-medium text-text-secondary uppercase tracking-wider">
                            Actions
                          </th>
                        </tr>
                      </thead>
                      <tbody className="bg-white divide-y divide-gray-200">
                        {category.activities.map((activity) => (
                          <tr key={activity.id} className="hover:bg-surface-light transition-colors">
                            <td className="px-4 py-4 text-sm text-text-primary">
                              {activity.description}
                            </td>
                            <td className="px-4 py-4 text-sm text-text-secondary">
                              {activity.location}
                            </td>
                            <td className="px-4 py-4 text-sm text-text-primary text-right font-medium">
                              {activity.quantity}
                            </td>
                            <td className="px-4 py-4 text-sm text-text-secondary">
                              {activity.unit}
                            </td>
                            <td className="px-4 py-4 text-center">
                              <div className="flex justify-center space-x-2">
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => handleEditActivity(activity.id)}
                                  className="text-primary hover:text-primary-dark"
                                  data-testid={`button-edit-activity-${activity.id}`}
                                >
                                  <Edit className="h-4 w-4" />
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => handleDeleteActivity(activity.id)}
                                  className="text-red-500 hover:text-red-700"
                                  data-testid={`button-delete-activity-${activity.id}`}
                                >
                                  <Trash2 className="h-4 w-4" />
                                </Button>
                              </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              );
            })}

            <Button
              variant="outline"
              onClick={handleAddCategory}
              className="w-full border-2 border-dashed border-primary text-primary hover:bg-primary hover:text-white"
              data-testid="button-add-category"
            >
              <Plus className="h-4 w-4 mr-2" />
              Add New Activity Category
            </Button>
          </div>

          {/* Timeline Summary */}
          <div className="mt-8 bg-surface-light rounded-xl p-6">
            <h3 className="text-lg font-semibold text-text-primary mb-4 flex items-center">
              <Calendar className="h-5 w-5 text-primary mr-2" />
              Estimated Timeline
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="text-center">
                <div className="text-2xl font-bold text-primary flex items-center justify-center">
                  <Clock className="h-5 w-5 mr-1" />
                  3-4
                </div>
                <div className="text-sm text-text-secondary">Weeks for Demolition</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-primary flex items-center justify-center">
                  <Clock className="h-5 w-5 mr-1" />
                  6-8
                </div>
                <div className="text-sm text-text-secondary">Weeks for Installation</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-primary flex items-center justify-center">
                  <Clock className="h-5 w-5 mr-1" />
                  2-3
                </div>
                <div className="text-sm text-text-secondary">Weeks for Finishing</div>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex justify-between mt-8">
            <Button
              variant="ghost"
              onClick={onPrevious}
              className="text-text-secondary hover:text-text-primary"
              data-testid="button-back"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Site Visit
            </Button>
            <Button 
              onClick={onNext} 
              className="btn-primary"
              data-testid="button-continue"
            >
              Continue to Pricing
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
